name: Callable deploy workflow

on:
  workflow_call:
    inputs:
      aws_environment:
        type: string
        required: true
      aws_region:
        type: string
        default: 'eu-central-1'
      deploy_backend_only:
        type: boolean
        default: false
      excel:
        type: boolean
        default: true
    secrets:
      aws_access_key_id:
        required: true
      SECRET_ACCESS_KEY:
        required: true
      azure:
        required: true

jobs:
  deploy:
    name: Deploy "synnovsh-kk--github-actions-fork"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Install packages
        run: ./install.sh

      - name: Update CDK Toolkit
        run: cd cdk && npx cdk bootstrap

      - name: Deploy backend to "synnovsh-kk--github-actions-fork"
        run: |
          cd cdk && npx cdk deploy \
          --require-approval never \
          --outputs-file outputs.json \
          --context ENV="synnovsh-kk--github-actions-fork" \

      - name: Prepare frontend "synnovsh-kk--github-actions-fork" deployment
        if: inputs.deploy_backend_only == false
        env:
          REACT_APP_USER_BRANCH: ${{ inputs.aws_environment == 'prod' && 'master' || 'dev' }}
        run: |
          cd cdk && npx ts-node --prefer-ts-exts hooks/hooks.ts && \
          npm run codegen && \
          cd ../frontend && echo $REACT_APP_USER_BRANCH >> .env && \
          CI='' npm run build \

      - name: Deploy frontend to "synnovsh-kk--github-actions-fork"
        if: inputs.deploy_backend_only == false
        run: cd frontend-cdk && npx cdk deploy --require-approval never
