name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      aws_environment:
        description: AWS environment
        type: choice
        options:
          - dev
          - prod
      deploy_backend_only:
        description: Deploy backend only
        type: boolean
        default: false

jobs: 
  deploy_dev_on_push_main:
    if: github.event_name == 'push'
    name: Deploy dev on push to main
    uses: ./.github/workflows/callable-deploy.yml
    with:
      aws_environment: dev
      deploy_backend_only: false
    secrets:
      aws_access_key_id: ${{ secrets.aws_access_key_id }}
      aws_secret_access_key: ${{ secrets.SECRET_ACCESS_KEY}}

  deploy_on_workflow_dispatch:
    if: github.event_name == 'workflow_dispatch'
    name: Deploy on dispatch
    uses: ./.github/workflows/callable-deploy.yml
    with:
      aws_environment: ${{ inputs.aws_environment }}
      deploy_backend_only: ${{ inputs.deploy_backend_only }}
    secrets:
      aws_access_key_id: ${{ inputs.aws_environment == 'prod' && secrets.aws_access_key_id }}
      aws_secret_access_key: ${{ inputs.aws_environment == 'prod' && secrets.PROD_AWS_SECRET_ACCESS_KEY }}