name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          ref: cypress
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: frontend
          start: npm start
          wait-on: 'http://localhost:3000'
          command: npx cypress run
          record: true
      - name: Upload video 📼
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: build
          if-no-files-found: error
          path: frontend/cypress